name: Rebuild docs
on:
  push:
    branches:
      - main

    paths:
      - 'docs/**'  # only rebuild docs webpage if docs/ folder is modified

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: ğŸ“‚Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: ğŸ› ï¸ Creating NICS working directory
        run: |
          cd ..
          mkdir __nics_work_dir__
          cd __nics_work_dir__
          cp -r ../mykit/docs/ .

      - name: ğŸSet up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: ğŸ±Installing NICS
        run: |
          python -m pip install --upgrade pip
          pip install -U nics

      - name: ğŸ“‚Checkout docs branch
        uses: actions/checkout@v3
        with:
          ref: docs

      - name: âš™ï¸ Compile
        run: |
          cd ..
          cd __nics_work_dir__
          nics _compile "$(pwd)/docs" "$(pwd)/../mykit"

      - name: ğŸš€Deploy
        run: |
          git config user.name "Nicholas Valentinus (via NICS)"
          git config user.email "nvfastplease@gmail.com"
          git add .
          git commit -m "NICS rebuild the docs"
          git push